services:
  ldapinator:
    build: .
    image: ldapinator
    container_name: ldapinator
    hostname: ldapinator
    restart: unless-stopped
    ports:
      - "3268:3268"
      - "3269:3269"
    volumes:
      - ./config:/app/config
